trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cat << EOF > .env
    AZURE_TEXT_ANALYTICS_ENDPOINT=$(AZURE_TEXT_ANALYTICS_ENDPOINT)
    AZURE_TEXT_ANALYTICS_KEY=$(AZURE_TEXT_ANALYTICS_KEY)
    AZURE_STORAGE_ACCOUNT_NAME=$(AZURE_STORAGE_ACCOUNT_NAME)
    AZURE_STORAGE_ACCOUNT_KEY=$(AZURE_STORAGE_ACCOUNT_KEY)
    AZURE_STORAGE_BLOB_ENDPOINT=$(AZURE_STORAGE_BLOB_ENDPOINT)
    AZURE_STORAGE_CONTAINER=$(AZURE_STORAGE_CONTAINER)
    ELASTIC_SEARCH_INDEX_NAME=$(ELASTIC_SEARCH_INDEX_NAME)
    ELASTIC_SEARCH_PIPELINE_NAME=$(ELASTIC_SEARCH_PIPELINE_NAME)
    OC_MASTER_SERVER_DNS=$(OC_MASTER_SERVER_DNS)
    OC_USERNAME=$(OC_USERNAME)
    OC_PASSWORD=$(OC_PASSWORD)
    SERVICE_PRINCIPAL_APP_ID=$(SERVICE_PRINCIPAL_APP_ID)
    SERVICE_PRINCIPAL_PASSWORD=$(SERVICE_PRINCIPAL_PASSWORD)
    SERVICE_PRINCIPAL_TENANT_ID=$(SERVICE_PRINCIPAL_TENANT_ID)
    CONTAINER_REGISTRY_URL=$(CONTAINER_REGISTRY_URL)
    BUILD_TAG=$(BUILD_TAG)
    BUILD_ID=$(Build.BuildId)
    EOF
  displayName: 'Create .env file'
- script: |
    docker build -t ci .
    docker run -v /var/run/docker.sock:/var/run/docker.sock ci
  displayName: 'Run CI'
