version: '3'

services:

  elasticsearch:
    build: elasticsearch
    environment:
      discovery.type: 'single-node'
      http.port: '9200'
      http.cors.enabled: 'true'
      http.cors.allow-origin: 'http://localhost:1358,http://127.0.0.1:1358'
      http.cors.allow-headers: 'X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization'
      http.cors.allow-credentials: 'true'
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ports:
      - 9200:9200
      - 9300:9300
    links:
      - textanalytics-sentiment

  elasticsearch-init:
    build: devtool
    command: >
      create-es-index
      create-es-pipeline --path /app/ingestion.json
      create-es-document --blob hello.docx
      create-es-document --blob hello.pdf
    environment:
      ES_HOST: 'elasticsearch'
      ES_PORT: '9200'
      ES_INDEX: '${ELASTIC_SEARCH_INDEX_NAME}'
      ES_PIPELINE: '${ELASTIC_SEARCH_PIPELINE_NAME}'
      AZURE_TEXT_ANALYTICS_ENDPOINT: 'http://textanalytics-sentiment:5000'
      AZURE_TEXT_ANALYTICS_KEY: 'not-used'
      AZURE_STORAGE_CONNECTION_STRING: '${AZURE_STORAGE_CONNECTION_STRING}'
      AZURE_STORAGE_CONTAINER: '${AZURE_STORAGE_CONTAINER}'
    links:
      - azurestorage
      - elasticsearch

  elasticsearch-ui:
    image: appbaseio/dejavu:3.3.1
    ports:
      - 1358:1358

  textanalytics-sentiment:
    image: mcr.microsoft.com/azure-cognitive-services/sentiment:latest
    command: ["Eula=accept", "Billing=${AZURE_TEXT_ANALYTICS_ENDPOINT}", "ApiKey=${AZURE_TEXT_ANALYTICS_KEY}"]
    ports:
      - 5000:5000

  azurestorage:
    image: arafato/azurite:2.6.5
    environment:
      executable: 'blob'
    ports:
      - 10000:10000

  azurestorage-init:
    build: azurestorage
    environment:
      AZURE_STORAGE_CONNECTION_STRING: '${AZURE_STORAGE_CONNECTION_STRING}'
      AZURE_STORAGE_CONTAINER: '${AZURE_STORAGE_CONTAINER}'
    links:
      - azurestorage
