version: '3'

services:

  cleanup:
    image: '${CONTAINER_REGISTRY_URL}/cleanup:latest'
    build: cleanup
    ports:
      - 8000:8000
    restart: always
    environment:
      PYTHONUNBUFFERED: 1